<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AcceptedPersons', 'doctrine');

/**
 * BaseAcceptedPersons
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $avdert_id
 * @property integer $user_id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * 
 * @method integer         getId()         Returns the current record's "id" value
 * @method integer         getAvdertId()   Returns the current record's "avdert_id" value
 * @method integer         getUserId()     Returns the current record's "user_id" value
 * @method timestamp       getCreatedAt()  Returns the current record's "created_at" value
 * @method timestamp       getUpdatedAt()  Returns the current record's "updated_at" value
 * @method AcceptedPersons setId()         Sets the current record's "id" value
 * @method AcceptedPersons setAvdertId()   Sets the current record's "avdert_id" value
 * @method AcceptedPersons setUserId()     Sets the current record's "user_id" value
 * @method AcceptedPersons setCreatedAt()  Sets the current record's "created_at" value
 * @method AcceptedPersons setUpdatedAt()  Sets the current record's "updated_at" value
 * 
 * @package    voyage
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAcceptedPersons extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('accepted_persons');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('avdert_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}