<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Advert', 'doctrine');

/**
 * BaseAdvert
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $type_id
 * @property integer $type_route_id
 * @property integer $direction_id
 * @property string $start_location
 * @property string $end_location
 * @property string $middle_location
 * @property timestamp $time
 * @property integer $p_number
 * @property string $comment
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * 
 * @method integer   getId()              Returns the current record's "id" value
 * @method integer   getTypeId()          Returns the current record's "type_id" value
 * @method integer   getTypeRouteId()     Returns the current record's "type_route_id" value
 * @method integer   getDirectionId()     Returns the current record's "direction_id" value
 * @method string    getStartLocation()   Returns the current record's "start_location" value
 * @method string    getEndLocation()     Returns the current record's "end_location" value
 * @method string    getMiddleLocation()  Returns the current record's "middle_location" value
 * @method timestamp getTime()            Returns the current record's "time" value
 * @method integer   getPNumber()         Returns the current record's "p_number" value
 * @method string    getComment()         Returns the current record's "comment" value
 * @method timestamp getCreatedAt()       Returns the current record's "created_at" value
 * @method timestamp getUpdatedAt()       Returns the current record's "updated_at" value
 * @method Advert    setId()              Sets the current record's "id" value
 * @method Advert    setTypeId()          Sets the current record's "type_id" value
 * @method Advert    setTypeRouteId()     Sets the current record's "type_route_id" value
 * @method Advert    setDirectionId()     Sets the current record's "direction_id" value
 * @method Advert    setStartLocation()   Sets the current record's "start_location" value
 * @method Advert    setEndLocation()     Sets the current record's "end_location" value
 * @method Advert    setMiddleLocation()  Sets the current record's "middle_location" value
 * @method Advert    setTime()            Sets the current record's "time" value
 * @method Advert    setPNumber()         Sets the current record's "p_number" value
 * @method Advert    setComment()         Sets the current record's "comment" value
 * @method Advert    setCreatedAt()       Sets the current record's "created_at" value
 * @method Advert    setUpdatedAt()       Sets the current record's "updated_at" value
 * 
 * @package    voyage
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdvert extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('advert');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('type_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('type_route_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('direction_id', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('start_location', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('end_location', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('middle_location', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('time', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('p_number', 'integer', 3, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 3,
             ));
        $this->hasColumn('comment', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}