<?php

/**
 * BasesfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property string $phone
 * @property string $photo
 * @property date $birthday
 * @property sfGuardUser $User
 * 
 * @method integer            getId()       Returns the current record's "id" value
 * @method integer            getUserId()   Returns the current record's "user_id" value
 * @method string             getPhone()    Returns the current record's "phone" value
 * @method string             getPhoto()    Returns the current record's "photo" value
 * @method date               getBirthday() Returns the current record's "birthday" value
 * @method sfGuardUser        getUser()     Returns the current record's "User" value
 * @method sfGuardUserProfile setId()       Sets the current record's "id" value
 * @method sfGuardUserProfile setUserId()   Sets the current record's "user_id" value
 * @method sfGuardUserProfile setPhone()    Sets the current record's "phone" value
 * @method sfGuardUserProfile setPhoto()    Sets the current record's "photo" value
 * @method sfGuardUserProfile setBirthday() Sets the current record's "birthday" value
 * @method sfGuardUserProfile setUser()     Sets the current record's "User" value
 * 
 * @package    voyage
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUserProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_profile');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('phone', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('photo', 'string', 200, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 200,
             ));
        $this->hasColumn('birthday', 'date', null, array(
             'type' => 'date',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}