<?php

/**
 * BaseAcceptedPersons
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $avdert_id
 * @property integer $user_id
 * @property Advert $Advert
 * 
 * @method integer         getId()        Returns the current record's "id" value
 * @method integer         getAvdertId()  Returns the current record's "avdert_id" value
 * @method integer         getUserId()    Returns the current record's "user_id" value
 * @method Advert          getAdvert()    Returns the current record's "Advert" value
 * @method AcceptedPersons setId()        Sets the current record's "id" value
 * @method AcceptedPersons setAvdertId()  Sets the current record's "avdert_id" value
 * @method AcceptedPersons setUserId()    Sets the current record's "user_id" value
 * @method AcceptedPersons setAdvert()    Sets the current record's "Advert" value
 * 
 * @package    voyage
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAcceptedPersons extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('accepted_persons');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'unique' => true,
             'autoincrement' => true,
             'primary' => true,
             'length' => 11,
             ));
        $this->hasColumn('avdert_id', 'integer', 11, array(
             'type' => 'integer',
             'unique' => false,
             'autoincrement' => false,
             'primary' => false,
             'notnull' => true,
             'length' => 11,
             ));
        $this->hasColumn('user_id', 'integer', 11, array(
             'type' => 'integer',
             'unique' => false,
             'autoincrement' => false,
             'primary' => false,
             'notnull' => true,
             'length' => 11,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Advert', array(
             'local' => 'id',
             'foreign' => 'advert_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}