<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AcceptedPersons', 'doctrine');

/**
 * BaseAcceptedPersons
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $advert_id
 * @property integer $user_id
 * @property integer $p_number
 * @property string $comment
 * @property Advert $Advert
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer         getId()          Returns the current record's "id" value
 * @method integer         getAdvertId()    Returns the current record's "advert_id" value
 * @method integer         getUserId()      Returns the current record's "user_id" value
 * @method integer         getPNumber()     Returns the current record's "p_number" value
 * @method string          getComment()     Returns the current record's "comment" value
 * @method Advert          getAdvert()      Returns the current record's "Advert" value
 * @method sfGuardUser     getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method AcceptedPersons setId()          Sets the current record's "id" value
 * @method AcceptedPersons setAdvertId()    Sets the current record's "advert_id" value
 * @method AcceptedPersons setUserId()      Sets the current record's "user_id" value
 * @method AcceptedPersons setPNumber()     Sets the current record's "p_number" value
 * @method AcceptedPersons setComment()     Sets the current record's "comment" value
 * @method AcceptedPersons setAdvert()      Sets the current record's "Advert" value
 * @method AcceptedPersons setSfGuardUser() Sets the current record's "sfGuardUser" value
 * 
 * @package    voyage
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAcceptedPersons extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('accepted_persons');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('advert_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('p_number', 'integer', 3, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 3,
             ));
        $this->hasColumn('comment', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Advert', array(
             'local' => 'advert_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}