<?php

/**
 * BaseTypeAdvert
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $typeAdvert
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getName()       Returns the current record's "name" value
 * @method Doctrine_Collection getTypeAdvert() Returns the current record's "typeAdvert" collection
 * @method TypeAdvert          setId()         Sets the current record's "id" value
 * @method TypeAdvert          setName()       Sets the current record's "name" value
 * @method TypeAdvert          setTypeAdvert() Sets the current record's "typeAdvert" collection
 * 
 * @package    voyage
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTypeAdvert extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('type_advert');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'unique' => true,
             'autoincrement' => true,
             'primary' => true,
             'length' => 11,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'unique' => false,
             'autoincrement' => false,
             'primary' => false,
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Advert as typeAdvert', array(
             'local' => 'type_id',
             'foreign' => 'id'));
    }
}