<?php

/**
 * BaseTypeRoute
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $typeRoute
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method string              getName()      Returns the current record's "name" value
 * @method Doctrine_Collection getTypeRoute() Returns the current record's "typeRoute" collection
 * @method TypeRoute           setId()        Sets the current record's "id" value
 * @method TypeRoute           setName()      Sets the current record's "name" value
 * @method TypeRoute           setTypeRoute() Sets the current record's "typeRoute" collection
 * 
 * @package    voyage
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTypeRoute extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('type_route');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'unique' => true,
             'autoincrement' => true,
             'primary' => true,
             'length' => 11,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'unique' => false,
             'autoincrement' => false,
             'primary' => false,
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Advert as typeRoute', array(
             'local' => 'type_route_id',
             'foreign' => 'id'));
    }
}