<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/04/28 17:45:35

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=voyage',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
