<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/04/28 17:45:41
$this->security = array (
  'secure' => 
  array (
    'is_secure' => false,
  ),
  'signin' => 
  array (
    'is_secure' => false,
  ),
  'signout' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
