<?php

/**
 * AcceptedPersonsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AcceptedPersonsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AcceptedPersonsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AcceptedPersons');
    }
}