<?php

/**
 * DirectionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DirectionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DirectionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Direction');
    }
}