<?php

/**
 * typeAdvertTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class typeAdvertTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object typeAdvertTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('typeAdvert');
    }
}