<?php

/**
 * TypeAdvertTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TypeAdvertTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TypeAdvertTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TypeAdvert');
    }
}