<?php

/**
 * TypeRouteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TypeRouteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TypeRouteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TypeRoute');
    }
}