# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }
  
sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }
  
sf_guard_forgot_password:
  url:  /sf_guard_forgot_password
  param: {module: sfGuardForgotPassword, action: index}

sf_guard_register:
  url:  /sf_guard_register
  param: {module: sfGuardRegister, action: index}

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

showAdvert:
  url: showAdvert/:id
  param: { module: viewAdverts, action: showAdvert }
  
removeAdvert:
  url: removeAdvert/:id
  param: { module: travelRoute, action: removeAdvert }
  
edit:
  url: edit/:id
  param: { module: travelRoute, action: editAdvert }
  
userprofile:
  url: user/profile/:id
  param: { module: userManagement, action: viewProfile }
  
bookForm:
  url: book/form/:id
  param: { module: bookAdvert, action: bookForm }
  
booked:
  url: booked/:id
  param: { module: bookAdvert, action: showBook }
  
bookDelete:
  url: book/delete/:id
  param: { module: bookAdvert, action: deleteBook }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
