# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css, pepper-grinder/jquery-ui-1.10.2.custom.min.css, jquery.ui.timepicker.css, search.css, nivo-slider.css, themes/default/default.css]

  javascripts:    [jquery-1.9.1.js, jquery-ui-1.10.2.custom.min.js, jquery.ui.timepicker.js, search_jsinput.js, jquery.nivo.slider.js]

  has_layout:     true
  layout:         layout
