<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/05/16 19:25:38

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=voyage',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
