<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/05/17 17:01:32
sfConfig::add(array(
  'mod_sfguardregister_enabled' => true,
  'mod_sfguardregister_view_class' => 'sfPHP',
));
