<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/05/17 17:01:06
sfConfig::add(array(
  'mod_sfguardforgotpassword_enabled' => true,
  'mod_sfguardforgotpassword_view_class' => 'sfPHP',
));
