AcceptedPersons:
  connection: doctrine
  tableName: accepted_persons
  actAs: [Timestampable]
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    advert_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    user_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    p_number:
      type: integer(3)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    comment:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Advert:
      local: advert_id
      foreign: id
      foreignAlias: AcceptedAdverts
      class: Advert
      type: one
      foreignType: many
      onDelete: CASCADE
    sfGuardUser:
      type:         one
      foreignType:  many
      class:        sfGuardUser
      local:        user_id
      foreign:      id
      onDelete:     CASCADE
      foreignAlias: UserAccount
Advert:
  connection: doctrine
  tableName: advert
  actAs: [Timestampable, Signable]
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    type_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    type_route_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    direction_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    start_location:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    end_location:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    middle_location:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    departure_date:
      type: date
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    return_date:
      type: date
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    time:
      type: time
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    p_number:
      type: integer(3)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    comment:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    TypeAdvert:
      local: type_id
      class: TypeAdvert
      foreign: id
      foreignAlias: TypeAdvertRecord
      foreignType: many
      type: one
    TypeRoute:
      local: type_route_id
      foreign: id
      foreignAlias: TypeRouteRecord
      class: TypeRoute
      foreignType: many
      type: one
    Direction:
      local: direction_id
      class: Direction
      foreign: id
      foreignAlias: DirectionRecord
      foreignType: many
      type: one
Direction:
  connection: doctrine
  tableName: direction
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
TypeAdvert:
  connection: doctrine
  tableName: type_advert
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
TypeRoute:
  connection: doctrine
  tableName: type_route
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
      
sfGuardUserProfile:
  columns:
    id: 
      type: integer
      primary: true
      autoincrement: true
    user_id:
      type: integer
    phone:
      type: string(20)
      notnull: true
    photo:
      type: string(200)
      notnull: false
    birthday:
      type: date
  relations:
    User:
      class: sfGuardUser
      local: user_id
      foreign: id
      type: one
      foreignType: one
      foreignAlias: Profile